language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn test
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
